# This file is autogenerated. Instead of editing this file, please use the
# migrations feature of ActiveRecord to incrementally modify your database, and
# then regenerate this schema definition.

ActiveRecord::Schema.define(:version => 6) do

  create_table "categories", :force => true do |t|
    t.column "name",             :string
    t.column "expenses_count",   :integer, :default => 0
    t.column "default_category", :boolean, :default => false
    t.column "user_id",          :integer
  end

  create_table "expenses", :force => true do |t|
    t.column "name",           :string
    t.column "created_at",     :datetime
    t.column "updated_at",     :datetime
    t.column "price_in_cents", :integer
    t.column "category_id",    :integer
    t.column "user_id",        :integer
  end

  create_table "expenses_tags", :id => false, :force => true do |t|
    t.column "tag_id",     :integer, :default => 0, :null => false
    t.column "expense_id", :integer, :default => 0, :null => false
  end

  create_table "sessions", :force => true do |t|
    t.column "session_id", :string
    t.column "data",       :text
    t.column "updated_at", :datetime
  end

  add_index "sessions", ["updated_at"], :name => "index_sessions_on_updated_at"
  add_index "sessions", ["session_id"], :name => "index_sessions_on_session_id"

  create_table "taggings", :force => true do |t|
    t.column "tag_id",        :integer
    t.column "taggable_id",   :integer
    t.column "taggable_type", :string
    t.column "created_at",    :datetime
  end

  create_table "tags", :force => true do |t|
    t.column "name", :string
  end

  create_table "users", :force => true do |t|
    t.column "login",                     :string
    t.column "email",                     :string
    t.column "crypted_password",          :string,   :limit => 40
    t.column "salt",                      :string,   :limit => 40
    t.column "created_at",                :datetime
    t.column "updated_at",                :datetime
    t.column "remember_token",            :string
    t.column "remember_token_expires_at", :datetime
    t.column "activation_code",           :string,   :limit => 40
    t.column "activated_at",              :datetime
    t.column "expenses_count",            :integer,                :default => 0
  end

end
